version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)

  build:
    commands:
      - docker build -t $ECR_REGISTRY/pc-builder/backend:$IMAGE_TAG -t $ECR_REGISTRY/pc-builder/backend:latest ./backend
      - docker build -t $ECR_REGISTRY/pc-builder/chroma:$IMAGE_TAG -t $ECR_REGISTRY/pc-builder/chroma:latest ./chroma

  post_build:
    commands:
      - docker push $ECR_REGISTRY/pc-builder/backend:$IMAGE_TAG
      - docker push $ECR_REGISTRY/pc-builder/backend:latest
      - docker push $ECR_REGISTRY/pc-builder/chroma:$IMAGE_TAG
      - docker push $ECR_REGISTRY/pc-builder/chroma:latest
      - printf '[{"name":"backend","imageUri":"%s"},{"name":"chroma","imageUri":"%s"}]' $ECR_REGISTRY/pc-builder/backend:$IMAGE_TAG $ECR_REGISTRY/pc-builder/chroma:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json